//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAssignment2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class moviedbEntities : DbContext
    {
        public moviedbEntities()
            : base("name=moviedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<moviebooking> moviebookings { get; set; }
        public virtual DbSet<Screen> Screens { get; set; }
        public virtual DbSet<theater> theaters { get; set; }
    }
}
