//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAssignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviebooking
    {
        public int bookingid { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> noofseats { get; set; }
        public Nullable<int> totalamount { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Screen Screen { get; set; }
    }
}
